# (14/04/23) DOESN'T WORK CURRENTLY
resources:
  - ../base/
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        labels:
          app: jupyter-web-app
          kustomize.component: jupyter-web-app
        name: jupyter-web-app-parameters-42k97gcbmb
        namespace: kubeflow
      data:
        JWA_APP_SECURE_COOKIES: "false"
