# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Automatically propose PRs for out-of-date GitHub actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      # Check for new versions weekly
      interval: weekly
    # Update all actions in a single PR
    groups:
      github-actions:
        patterns: ["*"]
    labels:
      - automation
      - gha-update
    # Only allow updates for actions maintained by GitHub
    allow:
      - dependency-name: "actions/*"
      - dependency-name: "azimuth-cloud/github-actions/*"

  - package-ecosystem: "helm"
    directories:
      - "/argocd-azimuth"
      # NOTE(sd109): BinderHub update doesn't work as of 2025-05-06.
      # See failed workflow:
      # https://github.com/azimuth-cloud/azimuth-charts/actions/runs/14863837842/job/41735465372
      # Possibly because there's still no stable BinderHub chart version?
      # Version list: https://hub.jupyter.org/helm-chart/
      # - "/binderhub-azimuth"
      - "/daskhub-azimuth"
      - "/jupyterhub-azimuth"
    schedule:
      interval: "weekly"
