{{- $name := "litellm-secrets" }}
{{- $existing := (get ((lookup "v1" "Secret" .Release.Namespace $name) | default dict) "data") | default dict }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "azimuth-inference.componentLabels" (dict "root" . "component" "litellm") | nindent 4 }}
type: Opaque
data:
  PROXY_MASTER_KEY: {{ include "azimuth-inference.idempotentSecret" (dict "existing" $existing "key" "PROXY_MASTER_KEY" "generated" (printf "sk-%s" (randAlphaNum 40))) }}
