{{- if and .Values.zenith.litellm.enabled }}
{{- $tile := .Values.zenith.litellm }}
{{- $name := include "azimuth-inference.gatewayFullname" . }}
---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Reservation
metadata:
  name: {{ $name }}
  labels:
    {{- include "azimuth-inference.componentLabels" (dict "root" . "component" "litellm") | nindent 4 }}
  annotations:
    azimuth.stackhpc.com/service-label: {{ $tile.label | quote }}
    azimuth.stackhpc.com/service-icon-url: {{ $tile.iconUrl | quote }}
    azimuth.stackhpc.com/service-description: {{ $tile.description | quote }}
spec:
  credentialSecretName: {{ $name }}-zenith-credential
---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Client
metadata:
  name: {{ $name }}
  labels:
    {{- include "azimuth-inference.componentLabels" (dict "root" . "component" "litellm") | nindent 4 }}
spec:
  reservationName: {{ $name }}
  upstream:
    serviceName: {{ .Release.Name }}-litellm
    port: 4000
  auth:
    skip: {{ $tile.skipAuth }}
{{- end }}
