{{- $name := "llama-api-key" }}
{{- $existing := (get ((lookup "v1" "Secret" .Release.Namespace $name) | default dict) "data") | default dict }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "azimuth-inference.labels" . | nindent 4 }}
type: Opaque
data:
  BACKEND_API_KEY: {{ include "azimuth-inference.idempotentSecret" (dict "existing" $existing "key" "BACKEND_API_KEY" "generated" (randAlphaNum 40)) }}
