{{- $name := "openwebui-secret-key" }}
{{- $existing := (get ((lookup "v1" "Secret" .Release.Namespace $name) | default dict) "data") | default dict }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $name }}"
  labels:
    {{- include "azimuth-inference.componentLabels" (dict "root" . "component" "open-webui") | nindent 4 }}
type: Opaque
data:
  secret_key: {{ include "azimuth-inference.idempotentSecret" (dict "existing" $existing "key" "secret_key" "generated" (randAlphaNum 40)) }}
