{{- range $model := (include "azimuth-inference.models" $ | fromYaml).models }}
{{- $ctx := dict "root" $ "model" $model }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "azimuth-inference.modelFullname" $ctx }}
  labels:
    {{- include "azimuth-inference.modelLabels" $ctx | nindent 4 }}
spec:
  type: {{ $model.service.type }}
  selector:
    {{- include "azimuth-inference.modelSelectorLabels" $ctx | nindent 4 }}
  ports:
    - name: api
      port: 80
      targetPort: api
      protocol: TCP
{{- end }}
