zenithClient:
  iconUrl: https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
  description:
  label: "Open WebUI Platform"

open-webui:
  ollama:
    gpu:
      enabled: true
      type: 'nvidia'
      number: 1
    replicaCount: 1
  