---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Azimuth creates a namespace per app, so using namespace suffix ensures 
  # unique cluster-scoped resource names
  name: jupyterhub-node-{{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyterhub-node-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jupyterhub-node-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: hub
  namespace: {{ .Release.Namespace }}