--- 
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: {{ .Values.namespace.flux }}
spec:
  targetNamespace: cert-manager
  kubeConfig:
    secretRef:
      name: {{ .Values.kubeconfig.name}}
      key: {{ .Values.kubeconfig.key}}
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: {{ .Values.namespace.flux }}
      interval: 5m
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    installCRDs: true
