---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack-charts
  namespace: {{ .Values.namespace.sources }}
spec:
  interval: 10m0s
  url: https://charts.jetstack.io
