apiVersion: v2
name: jupyterhub-azimuth
description: Multi-user Jupyter installation
type: application
version: 0.1.0
appVersion: 1.5.0
icon: https://raw.githubusercontent.com/jupyterhub/helm-chart/gh-pages/images/hublogo.svg
keywords: [jupyter, jupyterhub]

dependencies:
  - name: jupyterhub
    version: 2.0.0
    repository: https://jupyterhub.github.io/helm-chart/
