zenithClient:
  iconUrl: https://raw.githubusercontent.com/jupyter/design/master/logos/Logo%20Mark/logomark-orangebody-greyplanets/logomark-orangebody-greyplanets.png
  description:
  label: "Jupyter Notebook"

daskhub:
  dask-gateway:
    gateway:
      # auth:
      #   jupyterhub:
      #     apiToken: 448f787268fdef1d96c1054b88a28f405f0e636406996c7bcddcc40aa9e2fc2e
      extraConfig:
        optionHandler: |
          from dask_gateway_server.options import Options, Integer, Float, String
          def option_handler(options):
              if ":" not in options.image:
                  raise ValueError("When specifying an image you must also provide a tag")
              return {
                  "image": options.image,
              }
          c.Backend.cluster_options = Options(
              String("image", default="pangeo/base-notebook:2022.05.10", label="Image"),
              handler=option_handler,
          )

  jupyterhub:
    prePuller:
      hook:
        enabled: false
      continuous:
        enabled: false

    # The user scheduler is currently broken when there is only a single node
    scheduling:
      userScheduler:
        enabled: false

    # For the proxy, we only need a ClusterIP service as Zenith will punch it out
    proxy:
      service:
        type: ClusterIP
      chp:
        networkPolicy:
          enabled: false

    hub:
      # services:
      #   dask-gateway:
      #     apiToken: 448f787268fdef1d96c1054b88a28f405f0e636406996c7bcddcc40aa9e2fc2e
      networkPolicy:
        enabled: false
      # Configure the authentication to respect the X-Remote-User header sent by Zenith from Azimuth
      extraConfig:
        # Until https://github.com/jupyterhub/kubespawner/issues/498 is fixed
        # https://discourse.jupyter.org/t/advanced-z2jh-deeply-customizing-the-spawner/8432
        customspawner.py: |
          from kubespawner import KubeSpawner
        
          class CustomSpawner(KubeSpawner):
              def _build_common_labels(self, extra_labels):
                  labels = super()._build_common_labels(extra_labels)
                  label_username = "jupyter-" + labels['hub.jupyter.org/username']
                  labels['hub.jupyter.org/username'] = label_username
                  return labels

          c.JupyterHub.spawner_class = CustomSpawner

        # Configure the authentication to respect the X-Remote-User header sent by Zenith from Azimuth
        remoteuser.py: |
          from jupyterhub.auth import Authenticator
          from jupyterhub.handlers import BaseHandler

          from tornado import web

          class RemoteUserLoginHandler(BaseHandler):
              def get(self):
                  remote_user = self.request.headers.get("X-Remote-User")
                  if not remote_user:
                      raise web.HTTPError(401)
                  user = self.user_from_username(remote_user)
                  self.set_login_cookie(user)
                  next_url = self.get_next_url(user)
                  self.redirect(next_url)

          class RemoteUserAuthenticator(Authenticator):
              def get_handlers(self, app):
                  return [(r'/login', RemoteUserLoginHandler)]

              async def authenticate(self, *args, **kwargs):
                  raise NotImplementedError()

          c.JupyterHub.authenticator_class = RemoteUserAuthenticator

    singleuser:
      networkPolicy:
        enabled: false
      defaultUrl: /lab
      extraEnv:
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{{JUPYTER_IMAGE_SPEC}}'
        JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
      # cpu:
      #   limit: 1
      # memory:
      #   limit: '10G'
