resources:
  - ../base/
  - zenith-client.yml
  - zenith-reservation.yml
  - profile-cleanup.yml
  - istio-webhook-cleanup.yml

# Add some labels to make it easier to identify relevant resources
commonLabels:
  managed-by: kubeflow-azimuth-app

patches:
  # Convert istio's sidecar injector webhook resource to a pre-install
  # helm hooks to ensure that all other pods get the sidecar injected as
  # needed. Also add a custom label to allow us to clean them up in a
  # separate pre-delete hook.
  # NOTE: The '~1' in 'helm.sh~1hook' represents a '/' in the path name
  - patch: |-
      - op: add
        path: /metadata/annotations/helm.sh~1hook
        value: "pre-install"
      - op: add
        path: /metadata/annotations/helm.sh~1hook-weight
        value: "0"
      - op: add
        path: /metadata/annotations/helm.sh~1hook-delete-policy
        value: "hook-failed"
    target:
      kind: MutatingWebhookConfiguration
      name: istio-sidecar-injector

  # Convert all HorizontalPodAutoscaler resources to API v2
  # since v2beta2 was removed in Kubernetes 1.26
  - patch: |-
      - op: replace
        path: /apiVersion
        value: autoscaling/v2
    target:
      kind: HorizontalPodAutoscaler
      version: v2beta2

# Use StackHPC's ghcr for relevant container images
images:
- name: docker.io/istio/pilot:1.16.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/istio/pilot:1.16.0
- name: docker.io/istio/proxyv2:1.16.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/istio/proxyv2:1.16.0
- name: docker.io/kubeflowkatib/katib-controller:v0.15.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflowkatib/katib-controller:v0.15.0
- name: docker.io/kubeflowkatib/katib-db-manager:v0.15.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflowkatib/katib-db-manager:v0.15.0
- name: docker.io/kubeflowkatib/katib-ui:v0.15.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflowkatib/katib-ui:v0.15.0
- name: docker.io/kubeflownotebookswg/centraldashboard:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/centraldashboard:v1.7.0
- name: docker.io/kubeflownotebookswg/jupyter-web-app:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-web-app:v1.7.0
- name: docker.io/kubeflownotebookswg/kfam:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/kfam:v1.7.0
- name: docker.io/kubeflownotebookswg/notebook-controller:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/notebook-controller:v1.7.0
- name: docker.io/kubeflownotebookswg/poddefaults-webhook:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/poddefaults-webhook:v1.7.0
- name: docker.io/kubeflownotebookswg/profile-controller:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/profile-controller:v1.7.0
- name: docker.io/kubeflownotebookswg/tensorboard-controller:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/tensorboard-controller:v1.7.0
- name: docker.io/kubeflownotebookswg/tensorboards-web-app:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/tensorboards-web-app:v1.7.0
- name: docker.io/kubeflownotebookswg/volumes-web-app:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/volumes-web-app:v1.7.0
- name: docker.io/metacontrollerio/metacontroller:v2.0.4
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/metacontrollerio/metacontroller:v2.0.4
- name: gcr.io/arrikto/kubeflow/oidc-authservice:e236439
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/arrikto/kubeflow/oidc-authservice:e236439
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:33d78536e9b38dbb2ec2952207b48ff8e05acb48e7d28c2305bd0a0f7156198f
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:33d78536e9b38dbb2ec2952207b48ff8e05acb48e7d28c2305bd0a0f7156198f
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook@sha256:d217ab7e3452a87f8cbb3b45df65c98b18b8be39551e3e960cd49ea44bb415ba
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/eventing/cmd/webhook@sha256:d217ab7e3452a87f8cbb3b45df65c98b18b8be39551e3e960cd49ea44bb415ba
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256:2b484d982ef1a5d6ff93c46d3e45f51c2605c2e3ed766e20247d1727eb5ce918
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256:2b484d982ef1a5d6ff93c46d3e45f51c2605c2e3ed766e20247d1727eb5ce918
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:59b6a46d3b55a03507c76a3afe8a4ee5f1a38f1130fd3d65c9fe57fff583fa8d
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:59b6a46d3b55a03507c76a3afe8a4ee5f1a38f1130fd3d65c9fe57fff583fa8d
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:c3bbf3a96920048869dcab8e133e00f59855670b8a0bbca3d72ced2f512eb5e1
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:c3bbf3a96920048869dcab8e133e00f59855670b8a0bbca3d72ced2f512eb5e1
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256:caae5e34b4cb311ed8551f2778cfca566a77a924a59b775bd516fa8b5e3c1d7f
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256:caae5e34b4cb311ed8551f2778cfca566a77a924a59b775bd516fa8b5e3c1d7f
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:38f9557f4d61ec79cc2cdbe76da8df6c6ae5f978a50a2847c22cc61aa240da95
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:38f9557f4d61ec79cc2cdbe76da8df6c6ae5f978a50a2847c22cc61aa240da95
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook@sha256:a4ba0076df2efaca2eed561339e21b3a4ca9d90167befd31de882bff69639470
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook@sha256:a4ba0076df2efaca2eed561339e21b3a4ca9d90167befd31de882bff69639470
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping@sha256:763d648bf1edee2b4471b0e211dbc53ba2d28f92e4dae28ccd39af7185ef2c96
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping@sha256:763d648bf1edee2b4471b0e211dbc53ba2d28f92e4dae28ccd39af7185ef2c96
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256:bc13765ba4895c0fa318a065392d05d0adc0e20415c739e0aacb3f56140bf9ae
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256:bc13765ba4895c0fa318a065392d05d0adc0e20415c739e0aacb3f56140bf9ae
- name: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
- name: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
- name: gcr.io/ml-pipeline/api-server:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/api-server:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/cache-server:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/cache-server:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/frontend:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/frontend:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/metadata-envoy:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/metadata-envoy:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/metadata-writer:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/metadata-writer:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
- name: gcr.io/ml-pipeline/mysql:8.0.26
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/mysql:8.0.26
- name: gcr.io/ml-pipeline/persistenceagent:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/persistenceagent:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/scheduledworkflow:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/scheduledworkflow:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/viewer-crd-controller:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/viewer-crd-controller:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/visualization-server:2.0.0-alpha.7
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/visualization-server:2.0.0-alpha.7
- name: gcr.io/ml-pipeline/workflow-controller:v3.3.8-license-compliance
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/workflow-controller:v3.3.8-license-compliance
- name: gcr.io/tfx-oss-public/ml_metadata_store_server:1.5.0
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/tfx-oss-public/ml_metadata_store_server:1.5.0
- name: docker.io/kserve/kserve-controller:v0.10.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kserve/kserve-controller:v0.10.0
- name: docker.io/kserve/models-web-app:v0.10.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kserve/models-web-app:v0.10.0
- name: docker.io/kubeflow/training-operator:v1-5a5f92d
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflow/training-operator:v1-5a5f92d
- name: docker.io/kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.7.0
- name: docker.io/kubeflownotebookswg/jupyter-pytorch-full:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-pytorch-full:v1.7.0
- name: docker.io/kubeflownotebookswg/jupyter-scipy:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-scipy:v1.7.0
- name: docker.io/kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.7.0
- name: docker.io/kubeflownotebookswg/jupyter-tensorflow-full:v1.7.0
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-tensorflow-full:v1.7.0
- name: docker.io/library/mysql:8.0.29
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/library/mysql:8.0.29
- name: docker.io/library/python:3.7
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/library/python:3.7
- name: quay.io/jetstack/cert-manager-cainjector:v1.10.1
  newName: ghcr.io/stackhpc/azimuth-charts/quay.io/jetstack/cert-manager-cainjector:v1.10.1
- name: quay.io/jetstack/cert-manager-controller:v1.10.1
  newName: ghcr.io/stackhpc/azimuth-charts/quay.io/jetstack/cert-manager-controller:v1.10.1
- name: quay.io/jetstack/cert-manager-webhook:v1.10.1
  newName: ghcr.io/stackhpc/azimuth-charts/quay.io/jetstack/cert-manager-webhook:v1.10.1
- name: registry.k8s.io/coredns/coredns:v1.9.3
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/coredns/coredns:v1.9.3
- name: registry.k8s.io/etcd:3.5.6-0
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/etcd:3.5.6-0
- name: registry.k8s.io/kube-apiserver:v1.26.3
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/kube-apiserver:v1.26.3
- name: registry.k8s.io/kube-controller-manager:v1.26.3
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/kube-controller-manager:v1.26.3
- name: registry.k8s.io/kube-proxy:v1.26.3
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/kube-proxy:v1.26.3
- name: registry.k8s.io/kube-scheduler:v1.26.3
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/kube-scheduler:v1.26.3
- name: docker.io/tensorflow/tensorflow:2.5.1  
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/tensorflow/tensorflow:2.5.1