resources:
  - ../base/
  - zenith-client.yml
  - zenith-reservation.yml
  - profile-cleanup.yml
  - istio-webhook-cleanup.yml

# Add some labels to make it easier to identify relevant resources
commonLabels:
  managed-by: kubeflow-azimuth-app

patches:
  # Convert istio's sidecar injector webhook resource to a pre-install
  # helm hooks to ensure that all other pods get the sidecar injected as
  # needed. Also add a custom label to allow us to clean them up in a
  # separate pre-delete hook.
  # NOTE: The '~1' in 'helm.sh~1hook' represents a '/' in the path name
  - patch: |-
      - op: add
        path: /metadata/annotations/helm.sh~1hook
        value: "pre-install"
      - op: add
        path: /metadata/annotations/helm.sh~1hook-weight
        value: "0"
      - op: add
        path: /metadata/annotations/helm.sh~1hook-delete-policy
        value: "hook-failed"
    target:
      kind: MutatingWebhookConfiguration
      name: istio-sidecar-injector

  # Convert all HorizontalPodAutoscaler resources to API v2
  # since v2beta2 was removed in Kubernetes 1.26
  - patch: |-
      - op: replace
        path: /apiVersion
        value: autoscaling/v2
    target:
      kind: HorizontalPodAutoscaler
      version: v2beta2

# Use StackHPC's ghcr for relevant container images
images:
- name: docker.io/istio/pilot
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/istio/pilot
- name: docker.io/istio/proxyv2
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/istio/proxyv2
- name: docker.io/kubeflowkatib/katib-controller
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflowkatib/katib-controller
- name: docker.io/kubeflowkatib/katib-db-manager
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflowkatib/katib-db-manager
- name: docker.io/kubeflowkatib/katib-ui
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflowkatib/katib-ui
- name: docker.io/kubeflownotebookswg/centraldashboard
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/centraldashboard
- name: docker.io/kubeflownotebookswg/jupyter-web-app
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-web-app
- name: docker.io/kubeflownotebookswg/kfam
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/kfam
- name: docker.io/kubeflownotebookswg/notebook-controller
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/notebook-controller
- name: docker.io/kubeflownotebookswg/poddefaults-webhook
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/poddefaults-webhook
- name: docker.io/kubeflownotebookswg/profile-controller
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/profile-controller
- name: docker.io/kubeflownotebookswg/tensorboard-controller
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/tensorboard-controller
- name: docker.io/kubeflownotebookswg/tensorboards-web-app
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/tensorboards-web-app
- name: docker.io/kubeflownotebookswg/volumes-web-app
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/volumes-web-app
- name: docker.io/metacontrollerio/metacontroller
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/metacontrollerio/metacontroller
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/arrikto/kubeflow/oidc-authservice
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/eventing/cmd/controller
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/activator
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/controller
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/knative-releases/knative.dev/serving/cmd/webhook
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/kubebuilder/kube-rbac-proxy
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/kubebuilder/kube-rbac-proxy
- name: gcr.io/ml-pipeline/api-server
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/api-server
- name: gcr.io/ml-pipeline/cache-server
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/cache-server
- name: gcr.io/ml-pipeline/frontend
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/frontend
- name: gcr.io/ml-pipeline/metadata-envoy
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/metadata-envoy
- name: gcr.io/ml-pipeline/metadata-writer
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/metadata-writer
- name: gcr.io/ml-pipeline/minio
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/minio
- name: gcr.io/ml-pipeline/mysql
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/mysql
- name: gcr.io/ml-pipeline/persistenceagent
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/persistenceagent
- name: gcr.io/ml-pipeline/scheduledworkflow
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/scheduledworkflow
- name: gcr.io/ml-pipeline/viewer-crd-controller
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/viewer-crd-controller
- name: gcr.io/ml-pipeline/visualization-server
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/visualization-server
- name: gcr.io/ml-pipeline/workflow-controller
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/ml-pipeline/workflow-controller
- name: gcr.io/tfx-oss-public/ml_metadata_store_server
  newName: ghcr.io/stackhpc/azimuth-charts/gcr.io/tfx-oss-public/ml_metadata_store_server
- name: docker.io/kserve/kserve-controller
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kserve/kserve-controller
- name: docker.io/kserve/models-web-app
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kserve/models-web-app
- name: docker.io/kubeflow/training-operator
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflow/training-operator
- name: docker.io/kubeflownotebookswg/jupyter-pytorch-cuda-full
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-pytorch-cuda-full
- name: docker.io/kubeflownotebookswg/jupyter-pytorch-full
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-pytorch-full
- name: docker.io/kubeflownotebookswg/jupyter-scipy
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-scipy
- name: docker.io/kubeflownotebookswg/jupyter-tensorflow-cuda-full
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-tensorflow-cuda-full
- name: docker.io/kubeflownotebookswg/jupyter-tensorflow-full
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/kubeflownotebookswg/jupyter-tensorflow-full
- name: mysql
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/library/mysql
- name: python
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/library/python
- name: quay.io/jetstack/cert-manager-cainjector
  newName: ghcr.io/stackhpc/azimuth-charts/quay.io/jetstack/cert-manager-cainjector
- name: quay.io/jetstack/cert-manager-controller
  newName: ghcr.io/stackhpc/azimuth-charts/quay.io/jetstack/cert-manager-controller
- name: quay.io/jetstack/cert-manager-webhook
  newName: ghcr.io/stackhpc/azimuth-charts/quay.io/jetstack/cert-manager-webhook
- name: registry.k8s.io/coredns/coredns
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/coredns/coredns
- name: registry.k8s.io/etcd
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/etcd
- name: registry.k8s.io/kube-apiserver
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/kube-apiserver
- name: registry.k8s.io/kube-controller-manager
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/kube-controller-manager
- name: registry.k8s.io/kube-proxy
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/kube-proxy
- name: registry.k8s.io/kube-scheduler
  newName: ghcr.io/stackhpc/azimuth-charts/registry.k8s.io/kube-scheduler
- name: docker.io/tensorflow/tensorflow
  newName: ghcr.io/stackhpc/azimuth-charts/docker.io/tensorflow/tensorflow
