apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: kubeflow-profile
    istio-injection: enabled
    katib.kubeflow.org/metrics-collector-injection: enabled
    kubernetes.io/metadata.name: kubeflow-user-example-com
    pipelines.kubeflow.org/enabled: "true"
    serving.kubeflow.org/inferenceservice: enabled
    # Apply so kustomize patch can remove from all namespaces
    pod-security.kubernetes.io/enforce: restricted
  name: kubeflow-user-example-com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-viewer
  namespace: my-profile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-view
subjects:
- kind: ServiceAccount
  name: default-viewer
  namespace: kubeflow-user-example-com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-editor
  namespace: kubeflow-user-example-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: kubeflow-user-example-com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: admin
    user: user@example.com
  name: namespaceAdmin
  namespace: kubeflow-user-example-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user@example.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-viewer
  namespace: kubeflow-user-example-com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-editor
  namespace: kubeflow-user-example-com
