apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    app.kubernetes.io/name: poddefaults
    kustomize.component: poddefaults
    managed-by: kubeflow-azimuth-app
  name: admission-webhook-selfsigned-issuer
  namespace: kubeflow
spec:
  selfSigned: {}