apiVersion: v1
kind: Service
metadata:
  labels:
    managed-by: kubeflow-azimuth-app
  name: authservice
  namespace: istio-system
spec:
  ports:
  - name: http-authservice
    port: 8080
    targetPort: http-api
  publishNotReadyAddresses: true
  selector:
    app: authservice
    managed-by: kubeflow-azimuth-app
  type: ClusterIP