apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    managed-by: kubeflow-azimuth-app
  name: authservice-pvc
  namespace: istio-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi