apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
    managed-by: kubeflow-azimuth-app
  name: dex
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
      managed-by: kubeflow-azimuth-app
  template:
    metadata:
      labels:
        app: dex
        managed-by: kubeflow-azimuth-app
    spec:
      containers:
      - command:
        - dex
        - serve
        - /etc/dex/cfg/config.yaml
        env:
        - name: KUBERNETES_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: dex-oidc-client
        image: ghcr.io/dexidp/dex:v2.31.2
        name: dex
        ports:
        - containerPort: 5556
          name: http
        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: config
      serviceAccountName: dex
      volumes:
      - configMap:
          items:
          - key: config.yaml
            path: config.yaml
          name: dex
        name: config