apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    managed-by: kubeflow-azimuth-app
  name: dex
  namespace: auth
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /dex/
    route:
    - destination:
        host: dex.auth.svc.cluster.local
        port:
          number: 5556