apiVersion: v1
kind: Service
metadata:
  labels:
    katib.kubeflow.org/component: db-manager
    managed-by: kubeflow-azimuth-app
  name: katib-db-manager
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    katib.kubeflow.org/component: db-manager
    managed-by: kubeflow-azimuth-app
  type: ClusterIP