apiVersion: v1
kind: Service
metadata:
  labels:
    katib.kubeflow.org/component: mysql
    managed-by: kubeflow-azimuth-app
  name: katib-mysql
  namespace: kubeflow
spec:
  ports:
  - name: dbapi
    port: 3306
    protocol: TCP
  selector:
    katib.kubeflow.org/component: mysql
    managed-by: kubeflow-azimuth-app
  type: ClusterIP