apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    managed-by: kubeflow-azimuth-app
  name: katib-mysql
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi