apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kserve
    app.kubernetes.io/component: kserve-models-web-app
    app.kubernetes.io/name: kserve
    kustomize.component: kserve-models-web-app
    managed-by: kubeflow-azimuth-app
  name: kserve-models-web-app
  namespace: kubeflow