apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
    kustomize.component: metacontroller
    managed-by: kubeflow-azimuth-app
  name: meta-controller-service
  namespace: kubeflow