aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-notebooks-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
    managed-by: kubeflow-azimuth-app
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
  name: notebook-controller-kubeflow-notebooks-admin
rules: []