apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
    managed-by: kubeflow-azimuth-app
  name: notebook-controller-service-account
  namespace: kubeflow