apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
    managed-by: kubeflow-azimuth-app
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
  name: notebook-controller-kubeflow-notebooks-view
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  - notebooks/status
  verbs:
  - get
  - list
  - watch