apiVersion: v1
kind: Service
metadata:
  labels:
    kustomize.component: profiles
    managed-by: kubeflow-azimuth-app
  name: profiles-kfam
  namespace: kubeflow
spec:
  ports:
  - port: 8081
  selector:
    kustomize.component: profiles
    managed-by: kubeflow-azimuth-app