apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: kserve
    app.kubernetes.io/name: kserve
    managed-by: kubeflow-azimuth-app
  name: selfsigned-issuer
  namespace: kubeflow
spec:
  selfSigned: {}