apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: tensorboard-controller
    kustomize.component: tensorboard-controller
    managed-by: kubeflow-azimuth-app
  name: tensorboard-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tensorboard-controller-proxy-role
subjects:
- kind: ServiceAccount
  name: tensorboard-controller-controller-manager
  namespace: kubeflow