apiVersion: v1
data:
  TWA_APP_SECURE_COOKIES: "false"
  TWA_CLUSTER_DOMAIN: cluster.local
  TWA_PREFIX: /tensorboards
  TWA_USERID_HEADER: kubeflow-userid
  TWA_USERID_PREFIX: ""
kind: ConfigMap
metadata:
  labels:
    app: tensorboards-web-app
    kustomize.component: tensorboards-web-app
    managed-by: kubeflow-azimuth-app
  name: tensorboards-web-app-parameters-9cdtm8m796
  namespace: kubeflow