apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
    managed-by: kubeflow-azimuth-app
  name: volumes-web-app-service-account
  namespace: kubeflow