apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
    managed-by: kubeflow-azimuth-app
  name: volumes-web-app-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volumes-web-app-cluster-role
subjects:
- kind: ServiceAccount
  name: volumes-web-app-service-account
  namespace: kubeflow