zenithClient:
  iconUrl: https://raw.githubusercontent.com/argoproj/argo-cd/release-2.11/docs/assets/logo.png
  description:
  label: "Argo CD"

argo-cd:
  configs:
    params:
      server.insecure: true
      server.disable.auth: true
