apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: {{ .Release.Name }}
spec:
  selector:
    postgres-operator.crunchydata.com/role: pgadmin
  ports:
  - protocol: TCP
    port: 5050
