apiVersion: v2
name: aiworkbench-azimuth
description: AMD Enterprise AI Workbench
type: application
version: 0.1.0
appVersion: 0.1.0
# Placeholder
icon: https://avatars.githubusercontent.com/u/22750772


annotations:
  azimuth.stackhpc.com/label: AMD AI Workbench
