apiVersion: zenith.stackhpc.com/v1alpha1
kind: Client
metadata:
  name: {{ include "argocd-azimuth.fullname" . }}
  labels: {{ include "argocd-azimuth.labels" . | nindent 4 }}
spec:
  reservationName: {{ include "argocd-azimuth.fullname" . }}
  upstream:
    serviceName: {{ .Release.Name }}-argocd-server
