apiVersion: v1
name: postgres-azimuth
description: PostgreSQL RDBMS cluster.
type: application
version: 0.1.0
appVersion: 1.0.0
icon: https://raw.githubusercontent.com/postgres/pgweb/master/media/img/about/press/elephant.png
keywords: [postgres]

dependencies:
  - name: pgo
    version: 5.8.3
    repository: oci://registry.developers.crunchydata.com/crunchydata

annotations:
  azimuth.stackhpc.com/label: PostgreSQL
