name: Integration tests

on:
  # We use pull_request_target so that dependabot-created workflows can run
  # TODO: change to pull_request_target_after initial testing
  - pull_request

# Use the head ref for workflow concurrency, with cancellation
# This should mean that any previous workflows for a PR get cancelled when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  fail_on_remote:
    runs-on: ubuntu-latest
    steps:
      - name: PR must be from a branch in the azimuth-cloud/azimuth-capi-operator repo
        run: exit ${{ github.event.pull_request.head.repo.full_name == 'azimuth-cloud/azimuth-charts' && '0' || '1' }}

  detect_changes:
    name: Detect Files Changed
    permissions:
      contents: read
    needs: [fail_on_remote]
    runs-on: ubuntu-latest
    outputs:
      changed_apps: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Paths Filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            paths:
              argocd:
                - 'argocd-azimuth/**'
              binderhub:
                - 'binderhub-azimuth/**'
              daskhub:
                - 'daskhub-azimuth/**'
              jupyterhub:
                - 'jupyterhub-azimuth/**'
                - 'images/**'

  publish_artifacts:
    needs: [fail_on_remote]
    uses: ./.github/workflows/publish-charts.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
    permissions:
      contents: write
      id-token: write # needed for signing the images with GitHub OIDC Token
      packages: write # required for pushing container images
      security-events: write # required for pushing SARIF files
      pages: write
  
  run_azimuth_tests:
    name: Run Azimuth tests
    needs: [publish_artifacts, detect_changes]
    if: ${{ needs.detect_changes.outputs.changed_apps != '[]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Construct variables file
        id: construct_vars
        if: ${{ steps.filter.outputs.changes != '[]' }}
        run: |
          CHANGED_APPS='${{ needs.detect_changes.outputs.changed_apps }}'
          CHART_VERSION='${{ needs.publish_artifacts.outputs.chart-version }}'

          echo "extra_vars_yaml<<EOF" >> "$GITHUB_OUTPUT"

          echo "generate_tests_caas_suite_enabled: false" >> "$GITHUB_OUTPUT"
          echo "generate_tests_kubernetes_suite_enabled: false" >> "$GITHUB_OUTPUT"
          echo "azimuth_capi_operator_azimuth_charts_version: ${CHART_VERSION}" >> "$GITHUB_OUTPUT"

          for APP in $(echo "$CHANGED_APPS" | jq -r '.[]'); do
            echo "generate_tests_kubernetes_apps_test_case_${APP}_enabled: true" >> "$GITHUB_OUTPUT"
          done

          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Set up Azimuth environment
        uses: azimuth-cloud/azimuth-config/.github/actions/setup@temp-apps-test
        with:
          os-clouds: ${{ secrets.OS_CLOUDS }}
          environment-prefix: charts-ci
          target-cloud: ${{ vars.TARGET_CLOUD }}
          extra-vars: ${{ steps.construct_vars.outputs.extra_vars_yaml }}
        timeout-minutes: 180

      - name: Provision Azimuth
        uses: azimuth-cloud/azimuth-config/.github/actions/provision@temp-apps-test

      - name: Run Azimuth tests
        uses: azimuth-cloud/azimuth-config/.github/actions/test@temp-apps-test

      - name: Destroy Azimuth
        uses: azimuth-cloud/azimuth-config/.github/actions/destroy@temp-apps-test
        if: ${{ always() }}
