name: Integration tests

on:
  # We use pull_request_target so that dependabot-created workflows can run
  # TODO: change to pull_request_target_after initial testing
  - pull_request

# Use the head ref for workflow concurrency, with cancellation
# This should mean that any previous workflows for a PR get cancelled when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  fail_on_remote:
    runs-on: ubuntu-latest
    steps:
      - name: PR must be from a branch in the azimuth-cloud/azimuth-capi-operator repo
        run: exit ${{ github.event.pull_request.head.repo.full_name == 'azimuth-cloud/azimuth-charts' && '0' || '1' }}

  publish_artifacts:
    needs: [fail_on_remote]
    uses: ./.github/workflows/publish-charts.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
    permissions:
      contents: write
      id-token: write # needed for signing the images with GitHub OIDC Token
      packages: write # required for pushing container images
      security-events: write # required for pushing SARIF files
      pages: write
  
  run_azimuth_tests:
    name: Run Azimuth tests
    needs: [publish_artifacts]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Azimuth environment
        uses: azimuth-cloud/azimuth-config/.github/actions/setup@temp-apps-test  #TODO: revert
        with:
          os-clouds: ${{ secrets.OS_CLOUDS }}
          environment-prefix: charts-ci
          target-cloud: ${{ vars.TARGET_CLOUD }}
          extra-vars: |
            generate_tests_caas_suite_enabled: false
            generate_tests_kubernetes_suite_enabled: false
            generate_tests_kubernetes_apps_test_case_argocd_enabled: true
            generate_tests_kubernetes_apps_test_case_binderhub_enabled: true
            generate_tests_kubernetes_apps_test_case_daskhub_enabled: true
            generate_tests_kubernetes_apps_test_case_jupyterhub_enabled: true
            azimuth_capi_operator_azimuth_charts_version: ${{ needs.publish_artifacts.outputs.chart-version }}
        timeout-minutes: 180

      - name: Provision Azimuth
        uses: azimuth-cloud/azimuth-config/.github/actions/provision@temp-apps-test #TODO: revert

      - name: Run Azimuth tests
        uses: azimuth-cloud/azimuth-config/.github/actions/test@temp-apps-test #TODO: revert

      - name: Destroy Azimuth
        uses: azimuth-cloud/azimuth-config/.github/actions/destroy@temp-apps-test #TODO: revert
        if: ${{ always() }}
