---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "binderhub-azimuth.fullname" . | printf "%s-registry"}}
  labels: {{ include "binderhub-azimuth.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  strategy: {}
  template:
    metadata:
      labels:
        app: docker-registry # Must match spec.selector field of Service
    spec:
      containers:
      - image: docker.io/registry
        name: registry
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-storage
        # - mountPath: /certs
        #   name: tls-certs
        - mountPath: /auth
          name: registry-creds
        ports:
          - containerPort: 5000
            name: registry-http
        env:
        # - name: REGISTRY_AUTH
        #   value: silly
        # - name: REGISTRY_AUTH_SILLY_REALM
        #   value: test1
        # - name: REGISTRY_AUTH_SILLY_SERVICE
        #   value: test2
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd

        - name: REGISTRY_LOG_LEVEL
          value: debug

        # - name: REGISTRY_HTTP_TLS_CERTIFICATE
        #   value: /certs/tls.crt
        # - name: REGISTRY_HTTP_TLS_KEY
        #   value: /certs/tls.key
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: {{ include "binderhub-azimuth.fullname" . | printf "%s-registry"}}
        # - name: tls-certs
        #   secret:
        #     secretName: {{ include "binderhub-azimuth.fullname" . | printf "%s-registry-certs"}}
        - name: registry-creds
          secret:
            secretName: binderhub-registry-creds
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "binderhub-azimuth.fullname" . | printf "%s-registry"}}
  labels: {{ include "binderhub-azimuth.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      # TODO: Convert this to Helm value + UI input
      storage: {{ .Values.registry.storage.capacity }}
---
apiVersion: v1
kind: Service
metadata:
  # name: {{ .Values.binderhub.registry.url }}
  name: binderhub-registry
  labels: {{ include "binderhub-azimuth.labels" . | nindent 4 }}
spec:
  ports:
  - name: registry
    protocol: TCP
    port: 80
    targetPort: registry-http
    nodePort: 31782
  type: NodePort
  # type: ClusterIP
  selector:
    app: docker-registry
---
apiVersion: v1
data:
  htpasswd: dGVzdHVzZXI6JDJ5JDA1JFdqUVo2ZG1BeU0uNXIwbFk2eDdXTGV2Tk1JazQ1b1laMkpVTUloaW1VVEdSaU1nVXRGeU55
kind: Secret
metadata:
  name: binderhub-registry-creds
---
apiVersion: v1
kind: Secret
metadata:
  name: binderhub-registry-image-pull
type: kubernetes.io/dockerconfigjson
data:
  # TODO: Make this depend on the chart values using something like this: https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets
  .dockerconfigjson: {{"{\"auths\":{\"localhost:31782\":{\"auth\":\"dGVzdHVzZXI6dGVzdHBhc3N3b3Jk\"}}}" | b64enc }}