---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Client
metadata:
  name: {{ include "binderhub-azimuth.fullname" . }}
  labels: {{ include "binderhub-azimuth.labels" . | nindent 4 }}
spec:
  reservationName: {{ include "binderhub-azimuth.fullname" . }}
  upstream:
    serviceName: binder
---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Reservation
metadata:
  name: {{ include "binderhub-azimuth.fullname" . }}
  labels: {{ include "binderhub-azimuth.labels" . | nindent 4 }}
  annotations:
    azimuth.stackhpc.com/service-label: {{ quote .Values.zenithClient.label }}
    azimuth.stackhpc.com/service-icon-url: {{ .Values.zenithClient.iconUrl }}
    {{- with .Values.zenithClient.description }}
    azimuth.stackhpc.com/service-description: {{ quote . }}
    {{- end }}
spec:
  credentialSecretName: {{ include "binderhub-azimuth.fullname" . }}-credential
---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Client
metadata:
  name: {{ include "binderhub-azimuth.fullname" . | printf "%s-jupyterhub" }}
  labels: {{ include "binderhub-azimuth.labels" . | nindent 4 }}
spec:
  reservationName: {{ include "binderhub-azimuth.fullname" . | printf "%s-jupyterhub" }}
  upstream:
    serviceName: proxy-public
---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Reservation
metadata:
  name: {{ include "binderhub-azimuth.fullname" . | printf "%s-jupyterhub" }}
  labels: {{ include "binderhub-azimuth.labels" . | nindent 4 }}
  annotations:
    azimuth.stackhpc.com/service-label: "Placeholder"
spec:
  credentialSecretName: {{ include "binderhub-azimuth.fullname" . | printf "%s-jupyterhub" }}-credential
