apiVersion: v1
name: harbor-azimuth
description: Secure, open-source registry.
type: application
version: 0.1.0
appVersion: 1.0.0
icon: https://raw.githubusercontent.com/goharbor/harbor/refs/heads/main/docs/img/harbor_logo.png
keywords: [harbor]

dependencies:
  - name: harbor
    # Need https://github.com/goharbor/harbor-helm/pull/2257 to merge
    # before updating otherwise capi-operator helm install gets stuck due to yaml scanning errors
    version: 1.17.2
    repository: https://helm.goharbor.io

annotations:
  azimuth.stackhpc.com/label: Harbor
